CREATE DATABASE GA1;
USE GA1;

CREATE TABLE GA1(
   ID INT NOT NULL,
   NOMBRE VARCHAR(25),
   CORREO VARCHAR(50),
   PAIS VARCHAR(15),
   OCUPACION VARCHAR(25),
);
CREATE TABLE LOgA1(
   USUARIO VARCHAR(25) NOT NULL,
   CONTRASEÑA VARCHAR(25),
   ROLL VARCHAR (25)
   PRIMARY KEY (USUARIO),
);

INSERT INTO LOgA1(USUARIO, CONTRASEÑA, ROLL) VALUES('ANDREA', '123ASD', 'Administrador');
INSERT INTO LOgA1 VALUES('PABLOS', '789', 'Cliente');
INSERT INTO LOgA1 VALUES('ANNA', '963ÑLK', 'Secretaria');

SELECT * FROM LOgA1;

INSERT INTO GA1 VALUES (1, 'ANDREA MARROQUIN', 'ANDREA.FER.ALVAREZ@GMAIL.COM', 'GUATEMALA', 'ESTUDIANTE');
INSERT INTO GA1 VALUES (2, 'OLIVIA PASTO', 'OLIVPAS.32@GMAIL.COM', 'MEXICO', 'BAILARINA');
INSERT INTO GA1 VALUES (3, 'PABLO LAMBOTY', 'PABLO23BOTY@GMAIL.COM', 'COLOMBIA', 'MAESTRO');

SELECT * FROM GA1;